export const ADD_TO_CARD = "ADD_TO_CARD";
export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const TOOGLE_BRAND = "TOOGLE_BRAND";
export const TOOGLE_STOCK = "TOOGLE_STOCK";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";